# Use Ubuntu as the base image
FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update the system and install required tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    software-properties-common \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv \
    python3-openstackclient \
    python3-novaclient \
    python3-neutronclient \
    python3-cinderclient \
    python3-glanceclient \
    python3-keystoneclient \
    python3-zaqarclient \
    curl \
    wget \
    telnet \
    iputils-ping \
    nmap \
    netcat-openbsd \
    net-tools \
    traceroute \
    ipcalc \
    jq \
    vim \
    dnsutils \
    htop \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Optional: Install OpenStack CLI plugins for extended services
RUN apt install \
    python3-openstackclient \
    python3-osc-placement \
    python3-osc-lib \
    python3-openstacksdk

# Add the OpenStack clouds.yaml file
RUN mkdir -p /etc/openstack
COPY clouds.yaml /etc/openstack/clouds.yaml

# Set up a default working directory
WORKDIR /workspace

# Default entrypoint to keep the container running
CMD ["/bin/bash"]

