# mariadb:10.6.14-focal
ARG FROM=public.ecr.aws/docker/library/mariadb:11.4.8-noble
FROM ${FROM}

RUN set -ex ;\
    apt update ;\
    apt install -y --no-install-recommends \
        mariadb-server \
        python3-pip ;\
    rm -f /usr/lib/python*/EXTERNALLY-MANAGED ;\
    pip3 --no-cache-dir install \
      configparser \
      iso8601 \
      kubernetes \
      pymysql \
      pykube-ng ;\
    apt clean -y ;\
    rm -rf \
       /var/cache/debconf/* \
       /var/lib/apt/lists/* \
       /var/log/* \
       /tmp/* \
       /var/tmp/* ;\
    if getent passwd mysql > /dev/null; then \
        usermod -s /bin/false mysql; \
    else \
        groupadd -r mysql && useradd -r -g mysql -s /bin/false mysql; \
    fi ;\\\
    mkdir -p /var/lib/mysql /var/log/mysql /run/mysqld ;\\\
    chown -R mysql:mysql /var/lib/mysql /var/log/mysql /run/mysqld
