ARG FROM=quay.io/airshipit/ubuntu:jammy
# Build the manager binary
FROM --platform=$BUILDPLATFORM golang:1.23-bullseye as builder
ARG TARGETOS
ARG TARGETARCH

SHELL [ "/bin/bash", "-cex" ]
RUN apt-get update && apt-get install -y git

WORKDIR /usr/src/kubernetes-entrypoint
ADD . /usr/src/kubernetes-entrypoint

# If Makefile is missing, it means we are building with a thin context (only scripts).
# In that case, clone the source code.
RUN if [ ! -f Makefile ]; then \
        git init . && \
        git remote add origin https://github.com/airshipit/kubernetes-entrypoint.git && \
        git fetch --depth 1 origin master && \
        git checkout FETCH_HEAD ; \
    fi

ENV GO111MODULE=on
ENV GOTOOLCHAIN=auto

RUN go mod download
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -o bin/kubernetes-entrypoint



FROM ${FROM} as release

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://docs.airshipit.org/kubernetes-entrypoint' \
      org.opencontainers.image.source='https://opendev.org/airship/kubernetes-entrypoint' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

ENV DEBIAN_FRONTEND noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

COPY --from=builder /usr/src/kubernetes-entrypoint/bin/kubernetes-entrypoint /usr/local/bin/kubernetes-entrypoint

RUN apt update \
    && apt install -y --no-install-recommends coreutils

USER 65534
ENTRYPOINT [ "/usr/local/bin/kubernetes-entrypoint" ]