ARG FROM=ubuntu:noble
FROM ${FROM}

ENV DEBIAN_FRONTEND=noninteractive

# Install Python + pip
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-dev \
        build-essential \
        git \
        && rm -rf /var/lib/apt/lists/*

# Upgrade pip/setuptools/wheel
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel

# Install new-style OpenStack clients
RUN pip3 install --no-cache-dir --ignore-installed \
      cmd2 \
      python-openstackclient \
      barbicanclient \
      blazarclient \
      cinderclient \
      designateclient \
      glanceclient \
      heatclient \
      ironicclient \
      magnumclient \
      manilaclient \
      mistralclient \
      monascaclient \
      neutronclient \
      novaclient \
      octaviaclient \
      saharaclient \
      swiftclient \
      tackerclient \
      troveclient \
      vitrageclient \
      watcherclient \
      zaqarclient \
      zunclient

CMD ["bash"]
